name: GitHub Actions Demo
on: [push]
jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    #container: alpine:latest
    steps:
    - uses: actions/checkout@v2
    - name: run docker stuff
      uses: ./.github/workflows/docker
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ghmount/yolo
  other-job1:
    runs-on: ubuntu-latest
    steps:
    - run: ls -alh ghmount/
  other-job2:
    runs-on: ubuntu-latest
    steps:
    - run: sleep 10 && ls -alh ghmount/

