name: GitHub Actions Demo
on: [push]
jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    #container: alpine:latest
    - name: run docker stuff 
      run: docker run hello-world
